echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\" />\n";
echo "    <script src=\"https://kit.fontawesome.com/fc0bcca8a3.js\" crossorigin=\"anonymous\"></script>\n";
echo "    <link rel=\"stylesheet\" href=\"styless.css\" />\n";
echo "    <link href=\"https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700\" rel=\"stylesheet\">\n";
echo "\n";
echo "    <title>Sign In/Sign Up</title>\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "\n";
echo "    <header>\n";
echo "\n";
echo "        <nav>\n";
echo "            <a href=\"MainPage.html\" class=\"head\">TRAVELMANIA</a>\n";
echo "            <a href=\"book.php\" class=\"s2\">Book</a>\n";
echo "            <a href=\"hotels.php\" class=\"h1\">Hotels</a>\n";
echo "            <a href=\"tours.php\" class=\"t1\">Tours</a>\n";
echo "            <a href=\"MainPage.php\" class=\"h2\"><i class=\"\"></i> Home</a>\n";
echo "        </nav>\n";
echo "    </header>\n";
echo "\n";
echo "    <div class=\"container\" id=\"container\">\n";
echo "        <div class=\"form-container sign-up-container\">\n";
echo "            <form action=\"registration.php\" method=\"POST\">\n";
echo "                <h1>Create Account</h1>\n";
echo "                <div class=\"social-container\">\n";
echo "                    <a href=\"#\" class=\"social\"><i class=\"fab fa-facebook-f\"></i></a>\n";
echo "                    <a href=\"#\" class=\"social\"><i class=\"fab fa-google-plus-g\"></i></a>\n";
echo "                    <a href=\"#\" class=\"social\"><i class=\"fab fa-linkedin-in\"></i></a>\n";
echo "                </div>\n";
echo "                <span>OR <br> Use your Email for Registration</span>\n";
echo "                <input type=\"text\" name=\"username\" id=\"username\" placeholder=\"Name\" required/>\n";
echo "                <input type=\"email\" name=\"email\" id=\"email\" placeholder=\"Email\" required/>\n";
echo "                <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Password\" required/>\n";
echo "                <button>Sign Up</button>\n";
echo "            </form>\n";
echo "        </div>\n";
echo "        <div class=\"form-container sign-in-container\">\n";
echo "            <form action=\"match.php\" method=\"POST\">\n";
echo "                <h1>Sign In</h1>\n";
echo "                <div class=\"social-container\">\n";
echo "                    <a href=\"#\" class=\"social\"><i class=\"fab fa-facebook-f\"></i></a>\n";
echo "                    <a href=\"#\" class=\"social\"><i class=\"fab fa-google-plus-g\"></i></a>\n";
echo "                    <a href=\"#\" class=\"social\"><i class=\"fab fa-linkedin-in\"></i></a>\n";
echo "                </div>\n";
echo "                <span>or <br> Use your Account</span>\n";
echo "                <input type=\"text\" name=\"username\" id=\"username\" placeholder=\"Name\" required/>\n";
echo "                <input type=\"email\" name=\"email\" id=\"email\" placeholder=\"Email\" required/>\n";
echo "                <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Password\" required/>\n";
echo "                <a href=\"#\">Forgot your password?</a>\n";
echo "                <button>Sign in</button>\n";
echo "            </form>\n";
echo "        </div>\n";
echo "        <div class=\"overlay-container\">\n";
echo "            <div class=\"overlay\">\n";
echo "                <div class=\"overlay-panel overlay-left\">\n";
echo "                    <h1>Welcome Back!</h1>\n";
echo "                    <p>To keep connected please login with your personal info</p>\n";
echo "                    <button class=\"ghost\" id=\"signIn\">Sign In</button>\n";
echo "                </div>\n";
echo "                <div class=\"overlay-panel overlay-right\">\n";
echo "                    <h1>Hello</h1>\n";
echo "                    <p>Enter your personal details and <br> start journey with us.</p>\n";
echo "                    <button class=\"ghost\" id=\"signUp\">Sign Up</button>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <script src=\"sign-in.js\"></script>\n";
echo "</body>\n";
echo "\n";
echo "</html>";
